/* fingerprint.h: A compilation-time created file containing compilation time, 
closest version of git, and other information. Generated by fingerprint.py. */

#ifndef FINGERPRINT_H
#define FINGERPRINT_H

#define FP_COMPDATE "13:04:2018" //day:month:year
#define FP_COMPTIME "20:46:50" //hour:minute:second
#define FP_HOSTNAME "Rolis-MacBook-Pro"
#define FP_BRANCHNAME "abha_nandistor"
#define FP_HEXCOMMITHASH 0x90fdca7 
#define FP_STRCOMMITHASH "90fdca7"
#define FP_CLEANSTATUS false

#endif