language: java
sudo: false # run on travis's container infrastructure

jdk:
    - oraclejdk8

# TODO msebek: consolidate this logic into one script, then have both builders call it.
install:
    - curl -L https://services.gradle.org/distributions/gradle-2.7-bin.zip -o gradle-2.7-bin.zip
    - unzip gradle-2.7-bin.zip
    - export BUGGY_ROOT=`pwd`
    - export GRADLE_HOME=$BUGGY_ROOT/gradle-2.7
    - export GRADLE_BIN=$GRADLE_HOME/bin
    - export PATH=$PATH:$GRADLE_BIN

script:
    - echo 'the end is nigh, silly drivers'
    - ls; pwd; java -version
    - echo $PATH
    - echo $HOME
    - echo $BUGGY_ROOT
    - (cd real_time/surface_src/java_src/Alice && $GRADLE_BIN/gradle build)

notifications:
  slack: robobuggy:bnKltZMACloBdOGvYOINInyE

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ZkHnJ8JTj3QYYPbkoQA7/hbNpWmyj4/sv6ti8FFoz2Zmyrb+IRENXBopmgUUDKpagmdkCN44iEtVA5deVRTmuCbsF3YPJ2lGzeaP2tVvr3EjlB+xWsWIgMJVowXZcwrfWoKWOLOhjC+aW9Yl11q3bVyAMUm5w5HwqnacDZZwNPM="

addons:
  coverity_scan:
    project:
      name: "CMU-Robotics-Club/RoboBuggy"
      description: "Build submitted via Travis CI"
    notification_email: tdecker@andrew.cmu.edu
    build_command_prepend: ""
    build_command:   "cd real_time/surface_src/java_src/Alice && $GRADLE_BIN/gradle build"
    branch_pattern: coverity_scan