language: java
sudo: false # run on travis's container infrastructure

jdk:
    - oraclejdk8

# TODO msebek: consolidate this logic into one script, then have both builders call it.
install:
    - curl -L https://services.gradle.org/distributions/gradle-2.7-bin.zip -o gradle-2.7-bin.zip
    - unzip gradle-2.7-bin.zip
    - export BUGGY_ROOT=`pwd`
    - export GRADLE_HOME=$BUGGY_ROOT/gradle-2.7
    - export GRADLE_BIN=$GRADLE_HOME/bin
    - export PATH=$PATH:$GRADLE_BIN

script:
    - echo 'the end is nigh, silly drivers'
    - ls; pwd; java -version
    - echo $PATH
    - echo $HOME
    - echo $BUGGY_ROOT
    # for running the build and tests of the high level code
    - (cd real_time/surface_src/java_src/Alice && $GRADLE_BIN/gradle clean && $GRADLE_BIN/gradle build)
    - bash real_time/surface_src/java_src/Alice/travisStyleCheck.sh
    - bash real_time/arduino_src/travisStyleCheck.sh


notifications:
  slack: robobuggy:bnKltZMACloBdOGvYOINInyE
