language: java
sudo: false # run on travis's container infrastructure

jdk:
    - oraclejdk8

# TODO msebek: consolidate this logic into one script, then have both builders call it.
install:
    - curl -L https://services.gradle.org/distributions/gradle-2.7-bin.zip -o gradle-2.7-bin.zip
    - unzip gradle-2.7-bin.zip
    - export BUGGY_ROOT=`pwd`
    - export GRADLE_HOME=$BUGGY_ROOT/gradle-2.7
    - export GRADLE_BIN=$GRADLE_HOME/bin
    - export PATH=$PATH:$GRADLE_BIN

script:
    - echo 'the end is nigh, silly drivers'
    - ls; pwd; java -version
    - echo $PATH
    - echo $HOME
    - echo $BUGGY_ROOT
    # for running the build and tests of the high level code
    - (cd real_time/surface_src/java_src/Alice && $GRADLE_BIN/gradle build)
    # for viewing the find bugs error file
    - cat real_time/surface_src/java_src/Alice/build/reports/findbugs/main.xml
    # for counting the number of lines of java code that we have in alice
    - find real_time/surface_src/java_src/Alice/ -name '*.java' | xargs wc -l
    # for ensuring that the only println( is in logic error aka the console is not cluttered with debug info
    - (NUM=$(grep -r 'System.out.println(' real_time/surface_src/java_src/Alice/* | wc -l) && if [ $NUM = 1 ] the true else echo "Detected System.out.println() in Alice" && false fi

notifications:
  slack: robobuggy:bnKltZMACloBdOGvYOINInyE
