""" headercheck.py: 
* Description: This is a python script to create a header file defining
*   all of the rbsm message headers.  It reads from the file rbsm_headers.txt
*   and creates a headerfile, rbsmheaders.h, to define each message type.
*   This is done to ensure that both high level and low level are using the
*   same headers.
*
*  Note: To run this, the user must have python 2.7
*
*   By Sean Buckley
"""

import sys

def main():
    print("Now creating rbsmheaders.h...")

    #If rbsmheaders.h already exists, it will be overwritten
    file = open("../lib_avr/rbserialmessages/rbsmheaders.h", 'w')
    settingsFile = None
    try:
        settingsFile = open("../lib_avr/rbserialmessages/rbsm_headers.txt")
    except:
        print("Error! Unable to find rbsm_headers.txt\n")
        sys.exit()

    file.write("/* rbsmheaders.h: A compilation-time created file containing message \n")
    file.write("headers for rbsm. Generated by headercheck.py. */\n\n")
    file.write("#ifndef RBSMHEADERS_H\n#define RBSMHEADERS_H\n\n")

    for lineNum, line in enumerate(settingsFile):
        definition = line.split(", ")
        try:
            file.write("#define %s %s" %(definition[0], definition[1]))
        except:
            print("Error at line %d rbsm_headers.txt format! Is it 'HEADER, VALUE' ?" %(lineNum + 1))
            sys.exit()


    file.write("\n#endif")

    file.close()
    print("rbsmheaders.h created.\n")

main()